apiVersion: v1
kind: ServiceAccount
metadata:
  name: istioctl-debug
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioctl-limited-readonly
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs", "pods/portforward", "pods/exec", "configmaps", "secrets", "services", "endpoints", "namespaces", "nodes", "serviceaccounts/token", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authentication.istio.io", "security.istio.io", "telemetry.istio.io", "extensions.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validationwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istioctl-debug-limited-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istioctl-limited-readonly
subjects:
- kind: ServiceAccount
  name: istioctl-debug
  namespace: default

